"""add_request_response_logging_fields

Revision ID: 38ffc2ead19d
Revises: e6f6ccd99e25
Create Date: 2026-03-20 15:59:48.677952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ffc2ead19d'
down_revision: Union[str, Sequence[str], None] = 'e6f6ccd99e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('response_body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('request_headers', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('method', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('method')
        batch_op.drop_column('request_headers')
        batch_op.drop_column('response_body')
        batch_op.drop_column('request_body')

    # ### end Alembic commands ###
