"""Add capabilities and updated uploaded_files

Revision ID: afc97c98187f
Revises: e2c3c7a1b6ef
Create Date: 2026-03-17 05:45:51.347047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc97c98187f'
down_revision: Union[str, Sequence[str], None] = 'e2c3c7a1b6ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capabilities', sa.JSON(), nullable=True))

    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.alter_column('purpose',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.add_column(sa.Column('owner_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('size_bytes', sa.Integer(), nullable=False, server_default='0'))
        batch_op.drop_column('size')
        batch_op.drop_column('user_id')
        batch_op.create_index(batch_op.f('ix_uploaded_files_owner_user_id'), ['owner_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('size', sa.INTEGER(), nullable=False, server_default='0'))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_uploaded_files_owner_user_id'))
        batch_op.drop_column('owner_user_id')
        batch_op.drop_column('size_bytes')
        batch_op.alter_column('purpose',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('capabilities')

    # ### end Alembic commands ###
