"""Add consumer_api_keys table

Revision ID: f2bde0101af1
Revises: 584c4ec5ec61
Create Date: 2026-03-16 06:38:30.641739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2bde0101af1'
down_revision: Union[str, Sequence[str], None] = '584c4ec5ec61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumer_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumer_api_keys_id'), 'consumer_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_consumer_api_keys_key_hash'), 'consumer_api_keys', ['key_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumer_api_keys_key_hash'), table_name='consumer_api_keys')
    op.drop_index(op.f('ix_consumer_api_keys_id'), table_name='consumer_api_keys')
    op.drop_table('consumer_api_keys')
    # ### end Alembic commands ###
