from __future__ import annotations

import asyncio
import json
import time
import uuid
import shutil
from pathlib import Path
from typing import Any, AsyncGenerator, Dict, List, Optional

from backend.app.adapters.base import BaseAdapter
from backend.app.schemas.native import ImageGenerationRequest, VideoResult
from backend.app.schemas.openai import ChatCompletionChoice, ChatCompletionRequest, ChatCompletionResponse, ChatMessage


class McpCliAdapter(BaseAdapter):
    def __init__(self, profile: str | None = None):
        self.profile = profile

    async def _move_to_uploads(self, source_path_str: str) -> str:
        """Move a file generated by gemcli to the uploads directory and return its URL."""
        try:
            from pathlib import Path
            import uuid
            source_path = Path(source_path_str.strip())
            if not source_path.exists():
                return source_path_str
            
            # Ensure uploads directory exists
            uploads_dir = Path(__file__).resolve().parent.parent.parent.parent / "uploads"
            uploads_dir.mkdir(exist_ok=True)
            
            # Generate a unique destination name
            dest_filename = f"gen_{uuid.uuid4().hex}{source_path.suffix}"
            dest_path = uploads_dir / dest_filename
            
            # Move the file
            import shutil
            shutil.copy2(str(source_path), str(dest_path))
            
            # Return the full URL
            from backend.app.config import settings
            return f"http://192.168.88.81:{settings.API_PORT}/uploads/{dest_filename}"
        except Exception as e:
            print(f"Error moving file to uploads: {e}")
            return source_path_str

    async def _run_gemcli(self, args: List[str]) -> str:
        # Use absolute path to gemcli in .venv/bin
        import os
        from pathlib import Path

        # Determine the .venv path relative to the project root
        project_root = Path(__file__).resolve().parent.parent.parent.parent
        gemcli_path = project_root / ".venv" / "bin" / "gemcli"

        if not gemcli_path.exists():
            # Fallback for other environments if needed
            gemcli_path = "gemcli"
        else:
            gemcli_path = str(gemcli_path)

        cmd = [gemcli_path]
        if self.profile:
            cmd.extend(["--profile", self.profile])
        cmd.extend(args)

        # We assume gemcli is in the PATH
        process = await asyncio.create_subprocess_exec(
            *cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE
        )
        stdout, stderr = await process.communicate()
        
        stdout_str = stdout.decode().strip()
        stderr_str = stderr.decode().strip()

        if process.returncode != 0:
            raise Exception(f"gemcli failed: {stderr_str or stdout_str}")
        
        # Check for errors that might be printed to stdout but with a 0 return code
        if stdout_str.lower().startswith("error:") or "no valid authentication" in stdout_str.lower():
            raise Exception(stdout_str)

        return stdout_str

    async def chat_completion(self, request: ChatCompletionRequest) -> ChatCompletionResponse:
        # Simple implementation that just passes the last message to gemcli
        last_message = request.messages[-1].content if request.messages else ""
        output = await self._run_gemcli(["chat", last_message])

        return ChatCompletionResponse(
            id=f"chatcmpl-{uuid.uuid4()}",
            created=int(time.time()),
            model=request.model,
            choices=[
                ChatCompletionChoice(
                    index=0, message=ChatMessage(role="assistant", content=output.strip()), finish_reason="stop"
                )
            ],
            usage={"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0},
        )

    async def stream_chat(self, request: ChatCompletionRequest) -> AsyncGenerator[Dict[str, Any], None]:
        # gemcli doesn't support streaming output programmatically yet
        # Fallback to returning the whole chunk at once
        res = await self.chat_completion(request)
        chunk_id = f"chatcmpl-{uuid.uuid4()}"
        created = int(time.time())

        yield {
            "id": chunk_id,
            "object": "chat.completion.chunk",
            "created": created,
            "model": request.model,
            "choices": [{"index": 0, "delta": {"content": res.choices[0].message.content}, "finish_reason": None}],
        }
        yield {
            "id": chunk_id,
            "object": "chat.completion.chunk",
            "created": created,
            "model": request.model,
            "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}],
        }

    async def generate_image(self, request: ImageGenerationRequest) -> Dict[str, Any]:
        # gemcli image "prompt"
        output = await self._run_gemcli(["image", request.prompt])

        # Parse the output - gemcli might return a direct URL or a "saved to" message
        output_str = output.strip()
        url = await self._move_to_uploads(output_str)

        return {"created": int(time.time()), "data": [{"url": url}]}

    async def list_models(self) -> List[Dict[str, Any]]:
        """Return models available via gemini-web-mcp-cli (includes video/music/research capable ones)."""
        return [
            # Models confirmed to work through gemini-web-mcp-cli
            {"id": "gemini-2.0-flash", "display_name": "Gemini 2.0 Flash", "family": "gemini-2.0", "source": "mcpcli", "capabilities": {"chat": True}},
            {
                "id": "gemini-2.0-flash-exp",
                "display_name": "Gemini 2.0 Flash (Exp)",
                "family": "gemini-2.0",
                "source": "mcpcli",
                "capabilities": {"chat": True}
            },
            {
                "id": "gemini-2.0-pro-exp",
                "display_name": "Gemini 2.0 Pro (Exp)",
                "family": "gemini-2.0",
                "source": "mcpcli",
                "capabilities": {"chat": True}
            },
            {"id": "gemini-1.5-pro", "display_name": "Gemini 1.5 Pro", "family": "gemini-1.5", "source": "mcpcli", "capabilities": {"chat": True}},
            {"id": "gemini-1.5-flash", "display_name": "Gemini 1.5 Flash", "family": "gemini-1.5", "source": "mcpcli", "capabilities": {"chat": True}},
            # Imagen for image / video generation (used by mcp-cli internally)
            {"id": "imagen-3.0", "display_name": "Imagen 3.0 (Image Gen)", "family": "imagen", "source": "mcpcli", "capabilities": {"images": True}},
            {"id": "veo-2.0", "display_name": "Veo 2.0 (Video Gen)", "family": "veo", "source": "mcpcli", "capabilities": {"video": True}},
            {"id": "lyria-1.0", "display_name": "Lyria 1.0 (Music Gen)", "family": "lyria", "source": "mcpcli", "capabilities": {"music": True}},
        ]

    async def health_check(self) -> bool:
        try:
            await self._run_gemcli(["doctor"])
            return True
        except Exception:
            return False

    def _raise_if_auth_error(self, output: str):
        """Check if output contains an authentication error and raise a clear exception."""
        lowered = output.lower()
        if (
            "please login first" in lowered
            or "authentication failed" in lowered
            or "unauthorized" in lowered
            or "gemcli login" in lowered
            or lowered.startswith("error:")
        ):
            raise Exception(output.strip())

    async def generate_video(
        self,
        prompt: str,
        model: str | None,
        account_id: int | None,
        reference_files: list[Path] | None,
        options: dict | None,
    ) -> VideoResult:
        # Prepare arguments for gemcli video command
        args = ["video", prompt]

        # Add model if specified
        if model:
            args.extend(["--model", model])

        # Handle reference files if provided
        if reference_files:
            for ref_file in reference_files:
                args.extend(["--reference", str(ref_file)])

        output = await self._run_gemcli(args)
        self._raise_if_auth_error(output)

        url = await self._move_to_uploads(output.strip())
        return VideoResult(video_paths=[Path(url)], metadata={"model": model, "url": url})

    async def generate_music(self, prompt: str) -> str:
        # gemcli music "prompt"
        output = await self._run_gemcli(["music", prompt])
        self._raise_if_auth_error(output)
        return output.strip()

    async def deep_research(self, prompt: str) -> str:
        # gemcli research "prompt"
        output = await self._run_gemcli(["research", prompt])
        self._raise_if_auth_error(output)
        return output.strip()
