from __future__ import annotations

import asyncio
import json
import os
import shutil
import time
import uuid
from pathlib import Path
from typing import Any, AsyncGenerator, Dict, List, Optional

from backend.app.adapters.base import BaseAdapter
from backend.app.schemas.native import ImageGenerationRequest, VideoResult
from backend.app.schemas.openai import ChatCompletionChoice, ChatCompletionRequest, ChatCompletionResponse, ChatMessage


class McpCliAdapter(BaseAdapter):
    def __init__(self, profile: str | None = None, secure_1psid: str | None = None, secure_1psidts: str | None = None):
        self.profile = profile
        self.secure_1psid = secure_1psid
        self.secure_1psidts = secure_1psidts

    async def _sync_auth(self):
        """Sync cookies from the database to the gemcli profile auth.json file."""
        if not self.secure_1psid:
            return
            
        try:
            # We'll project into multiple locations to ensure gemcli finds it
            profile_name = "default" 
            gemcli_root = Path.home() / ".gemini-web-mcp-cli"
            
            # Paths to ensure
            profile_dir = gemcli_root / "profiles" / profile_name
            profile_dir.mkdir(parents=True, exist_ok=True)
            chrome_profile = gemcli_root / "chrome-profiles" / profile_name
            chrome_profile.mkdir(parents=True, exist_ok=True)
            
            auth_file = profile_dir / "auth.json"
            auth_data = {
                "cookies": {
                    "__Secure-1PSID": self.secure_1psid,
                    "__Secure-1PSIDTS": self.secure_1psidts or ""
                },
                "chrome_profile_path": str(chrome_profile),
                "last_refreshed": int(time.time())
            }
            
            with open(auth_file, "w") as f_out:
                json.dump(auth_data, f_out, indent=2)
                
            # Also sync the specific profile folder if a label is used
            if self.profile and self.profile != "default":
                label_dir = gemcli_root / "profiles" / self.profile
                label_dir.mkdir(parents=True, exist_ok=True)
                with open(label_dir / "auth.json", "w") as f_out:
                    json.dump(auth_data, f_out, indent=2)
                    
        except Exception as e:
            print(f"Error syncing mcpcli auth: {e}")

    async def _move_to_uploads(self, source_path_str: str) -> str:
        """Move a file generated by gemcli to the uploads directory and return its URL."""
        try:
            source_path = Path(source_path_str.strip())
            if not source_path.exists():
                return source_path_str
            
            # Ensure uploads directory exists
            uploads_dir = Path(__file__).resolve().parent.parent.parent.parent / "uploads"
            uploads_dir.mkdir(exist_ok=True)
            
            # Generate a unique destination name
            dest_filename = f"gen_{uuid.uuid4().hex}{source_path.suffix}"
            dest_path = uploads_dir / dest_filename
            
            # Move the file
            shutil.copy2(str(source_path), str(dest_path))
            
            # Return the full URL
            from backend.app.config import settings
            return f"http://192.168.88.81:{settings.API_PORT}/uploads/{dest_filename}"
        except Exception as e:
            print(f"Error moving file to uploads: {e}")
            return source_path_str

    async def _run_gemcli(self, args: List[str]) -> str:
        # 1. Sync auth cookies before running
        await self._sync_auth()
        
        # Use absolute path to gemcli in .venv/bin
        project_root = Path(__file__).resolve().parent.parent.parent.parent
        gemcli_path = project_root / ".venv" / "bin" / "gemcli"

        if not gemcli_path.exists():
            gemcli_path = "gemcli"
        else:
            gemcli_path = str(gemcli_path)

        cmd = [gemcli_path]
        if self.profile:
            cmd.extend(["--profile", self.profile])
        cmd.extend(args)

        process = await asyncio.create_subprocess_exec(
            *cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE
        )
        stdout, stderr = await process.communicate()
        
        stdout_str = stdout.decode().strip()
        stderr_str = stderr.decode().strip()

        if process.returncode != 0:
            raise Exception(f"gemcli failed: {stderr_str or stdout_str}")
        
        if stdout_str.lower().startswith("error:") or "no valid authentication" in stdout_str.lower():
            raise Exception(stdout_str)

        return stdout_str

    async def chat_completion(self, request: ChatCompletionRequest) -> ChatCompletionResponse:
        # Simple implementation that just passes the last message to gemcli
        last_message = request.messages[-1].content if request.messages else ""
        output = await self._run_gemcli(["chat", last_message])

        return ChatCompletionResponse(
            id=f"chatcmpl-{uuid.uuid4()}",
            created=int(time.time()),
            model=request.model,
            choices=[
                ChatCompletionChoice(
                    index=0, message=ChatMessage(role="assistant", content=output.strip()), finish_reason="stop"
                )
            ],
            usage={"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0},
        )

    async def stream_chat(self, request: ChatCompletionRequest) -> AsyncGenerator[Dict[str, Any], None]:
        res = await self.chat_completion(request)
        chunk_id = f"chatcmpl-{uuid.uuid4()}"
        created = int(time.time())

        yield {
            "id": chunk_id,
            "object": "chat.completion.chunk",
            "created": created,
            "model": request.model,
            "choices": [{"index": 0, "delta": {"content": res.choices[0].message.content}, "finish_reason": None}],
        }
        yield {
            "id": chunk_id,
            "object": "chat.completion.chunk",
            "created": created,
            "model": request.model,
            "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}],
        }

    async def generate_image(self, request: ImageGenerationRequest) -> Dict[str, Any]:
        # Use -o to save image to a temp file; without -o gemcli renders to screen
        import tempfile
        suffix = ".png"
        with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as tmp:
            tmp_path = tmp.name
        args = ["image", request.prompt, "-o", tmp_path]
        await self._run_gemcli(args)
        url = await self._move_to_uploads(tmp_path)
        return {"created": int(time.time()), "data": [{"url": url}]}

    async def list_models(self) -> List[Dict[str, Any]]:
        """Return models available via gemini-web-mcp-cli."""
        return [
            {"id": "gemini-2.0-flash", "display_name": "Gemini 2.0 Flash", "family": "gemini-2.0", "source": "mcpcli", "capabilities": {"chat": True}},
            {"id": "gemini-2.0-flash-exp", "display_name": "Gemini 2.0 Flash (Exp)", "family": "gemini-2.0", "source": "mcpcli", "capabilities": {"chat": True}},
            {"id": "gemini-2.0-pro-exp", "display_name": "Gemini 2.0 Pro (Exp)", "family": "gemini-2.0", "source": "mcpcli", "capabilities": {"chat": True}},
            {"id": "gemini-1.5-pro", "display_name": "Gemini 1.5 Pro", "family": "gemini-1.5", "source": "mcpcli", "capabilities": {"chat": True}},
            {"id": "gemini-1.5-flash", "display_name": "Gemini 1.5 Flash", "family": "gemini-1.5", "source": "mcpcli", "capabilities": {"chat": True}},
            {"id": "imagen-3.0", "display_name": "Imagen 3.0 (Image Gen)", "family": "imagen", "source": "mcpcli", "capabilities": {"images": True}},
            {"id": "veo-2.0", "display_name": "Veo 2.0 (Video Gen)", "family": "veo", "source": "mcpcli", "capabilities": {"video": True}},
            {"id": "lyria-1.0", "display_name": "Lyria 1.0 (Music Gen)", "family": "lyria", "source": "mcpcli", "capabilities": {"music": True}},
        ]

    async def health_check(self) -> bool:
        try:
            await self._run_gemcli(["doctor"])
            return True
        except Exception:
            return False

    def _raise_if_auth_error(self, output: str):
        lowered = output.lower()
        if any(msg in lowered for msg in ["please login first", "authentication failed", "unauthorized", "gemcli login"]) or lowered.startswith("error:"):
            raise Exception(output.strip())

    async def generate_video(self, prompt: str, model: str | None, account_id: int | None, reference_files: list[Path] | None, options: dict | None) -> VideoResult:
        import tempfile
        with tempfile.NamedTemporaryFile(suffix=".mp4", delete=False) as tmp:
            tmp_path = tmp.name
        args = ["video", prompt, "-o", tmp_path]
        # gemcli video only accepts: flash, pro, thinking — map our model aliases
        _MODEL_MAP = {"veo-2.0": "flash", "veo-pro": "pro", "veo-thinking": "thinking"}
        gemcli_model = _MODEL_MAP.get(model or "", None) if model else None
        if gemcli_model:
            args.extend(["--model", gemcli_model])
        if reference_files:
            for ref_file in reference_files:
                args.extend(["--reference", str(ref_file)])
        await self._run_gemcli(args)
        url = await self._move_to_uploads(tmp_path)
        return VideoResult(video_paths=[Path(url)], metadata={"model": model, "url": url})

    async def generate_music(self, prompt: str) -> str:
        output = await self._run_gemcli(["music", prompt])
        return output.strip()

    async def deep_research(self, prompt: str) -> str:
        output = await self._run_gemcli(["research", prompt])
        return output.strip()
