from typing import Optional
import asyncio
import uuid
from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from sqlalchemy.ext.asyncio import AsyncSession
from backend.app.db.engine import get_db, AsyncSessionLocal
from backend.app.db.models import User, Job
from backend.app.auth.api_key_auth import get_user_by_key_or_jwt
from backend.app.jobs.manager import JobManager
from backend.app.api.openai.chat_completions import adapter_router
from pydantic import BaseModel

router = APIRouter(prefix="/native/tasks", tags=["native-tasks"])


class TaskRequest(BaseModel):
    prompt: str
    model: Optional[str] = None
    reference_file_ids: list[str] = []
    account_id: Optional[int] = None


async def run_task_background(job_id: int, task_type: str, request_data: dict):
    async with AsyncSessionLocal() as db:
        await JobManager.update_job(db, job_id, "processing", 0.1)

        prompt = request_data.get("prompt", "")
        model = request_data.get("model", None)
        reference_file_ids = request_data.get("reference_file_ids", [])
        account_id = request_data.get("account_id", None)

        try:
            from backend.app.adapters.router import adapter_router

            if task_type == "video":
                from backend.app.adapters.mcpcli_adapter import McpCliAdapter
                from pathlib import Path

                adapter = McpCliAdapter()
                video_result = await adapter.generate_video(
                    prompt, model=model, account_id=account_id, reference_files=reference_file_ids, options={}
                )
                result = str(video_result.video_paths[0]) if video_result.video_paths else ""
            elif task_type == "music":
                from backend.app.adapters.mcpcli_adapter import McpCliAdapter

                adapter = McpCliAdapter()
                result = await adapter.generate_music(prompt)
            elif task_type == "research":
                from backend.app.adapters.mcpcli_adapter import McpCliAdapter

                adapter = McpCliAdapter()
                result = await adapter.deep_research(prompt)
            elif task_type == "image":
                from backend.app.schemas.native import ImageGenerationRequest

                req = ImageGenerationRequest(
                    prompt=prompt, model=model, reference_file_ids=reference_file_ids, account_id=account_id
                )
                res = await adapter_router.generate_image(req)
                data = res.get("data", [])
                if not data:
                    raise ValueError("No images were generated by the model.")
                result = data[0].get("url")
            else:
                raise ValueError(f"Unknown task type: {task_type}")

            await JobManager.update_job(db, job_id, "completed", 1.0, result_url=result)
        except Exception as e:
            error_msg = str(e)
            if "No valid authentication" in error_msg or "Session expired" in error_msg or "gemcli login" in error_msg:
                error_msg = (
                    "Video/Music/Research require a Google account with Gemini Advanced. "
                    "Please run 'gemcli login' interactively in a terminal with a Gemini Advanced account, "
                    "or use the Admin Panel to import browser cookies. "
                    f"Original error: {error_msg}"
                )
            await JobManager.update_job(db, job_id, "failed", 1.0, error=error_msg)


@router.post("/image")
async def create_image_task(
    request: TaskRequest,
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_user_by_key_or_jwt),
):
    job = await JobManager.create_job(db, None, request.account_id, "image")
    background_tasks.add_task(run_task_background, job.id, "image", request.model_dump())
    return {"job_id": job.id, "status": "pending"}


@router.post("/video")
async def create_video_task(
    request: TaskRequest,
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_user_by_key_or_jwt),
):
    # 1. Create RequestLog (Skipped for brevity, but should be there)
    # 2. Create Job
    job = await JobManager.create_job(db, None, request.account_id, "video")

    # 3. Queue task
    background_tasks.add_task(run_task_background, job.id, "video", request.model_dump())

    return {"job_id": job.id, "status": "pending"}


@router.post("/music")
async def create_music_task(
    request: TaskRequest,
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_user_by_key_or_jwt),
):
    job = await JobManager.create_job(db, None, request.account_id, "music")
    background_tasks.add_task(run_task_background, job.id, "music", request.model_dump())
    return {"job_id": job.id, "status": "pending"}


@router.post("/research")
async def create_research_task(
    request: TaskRequest,
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_user_by_key_or_jwt),
):
    job = await JobManager.create_job(db, None, request.account_id, "research")
    background_tasks.add_task(run_task_background, job.id, "research", request.model_dump())
    return {"job_id": job.id, "status": "pending"}


@router.get("/{job_id}")
async def get_task_status(
    job_id: int, db: AsyncSession = Depends(get_db), user: User = Depends(get_user_by_key_or_jwt)
):
    job = await db.get(Job, job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    return {
        "job_id": job.id,
        "type": job.job_type,
        "status": job.status,
        "progress": job.progress_pct,
        "result_url": job.result_url,
        "error": job.error,
    }
