from pathlib import Path
from typing import Optional

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from backend.app.auth.api_key_auth import get_user_by_key_or_jwt
from backend.app.config import BASE_DIR
from backend.app.db.engine import AsyncSessionLocal, get_db
from backend.app.db.models import Job, UploadedFile, User
from backend.app.jobs.manager import JobManager
from backend.app.schemas.native import ImageGenerationRequest
from backend.app.adapters.router import adapter_router
from backend.app.storage.files import FileStorage
from pydantic import BaseModel


async def _load_reference_bytes(file_ids: list[str]) -> bytes | None:
    """Load the first valid reference file's bytes from local storage."""
    if not file_ids:
        return None
    storage = FileStorage(base_dir=BASE_DIR / "uploads")
    for file_id in file_ids:
        try:
            meta = storage.get_metadata(file_id)
            return Path(meta.storage_path).read_bytes()
        except Exception:
            continue
    return None

router = APIRouter(prefix="/native/tasks", tags=["native-tasks"])


class TaskRequest(BaseModel):
    prompt: str
    model: Optional[str] = None
    reference_file_ids: list[str] = []
    account_id: Optional[int] = None
    adapter: Optional[str] = None  # "webapi" or "mcpcli" or None (auto)


async def run_task_background(job_id: int, task_type: str, request_data: dict):
    async with AsyncSessionLocal() as db:
        await JobManager.update_job(db, job_id, "processing", 0.1)
        prompt = request_data.get("prompt", "")
        model = request_data.get("model")
        reference_file_ids = request_data.get("reference_file_ids", [])
        account_id = request_data.get("account_id")
        adapter = request_data.get("adapter")
        try:
            if task_type == "video":
                res = await adapter_router.generate_video(prompt, model=model, account_id=account_id, reference_files=[Path(ref) for ref in reference_file_ids], options={}, adapter=adapter)
                # Prefer the url from metadata to avoid Path() mangling http:// into http:/
                result = res.metadata.get("url", "") or (str(res.video_paths[0]) if res.video_paths else "")
            elif task_type == "music":
                result = await adapter_router.generate_music(prompt, account_id=account_id, adapter=adapter)
            elif task_type == "research":
                result = await adapter_router.generate_research(prompt, account_id=account_id, adapter=adapter)
            elif task_type == "image":
                img_request = ImageGenerationRequest(prompt=prompt, model=model, reference_file_ids=reference_file_ids, account_id=account_id)
                if reference_file_ids:
                    # Edit mode: load the reference image bytes and call edit_image
                    reference_bytes = await _load_reference_bytes(reference_file_ids)
                    import asyncio as _asyncio
                    _task = _asyncio.create_task(
                        adapter_router.edit_image(img_request, reference_file=reference_bytes, adapter=adapter)
                    )
                    done, pending = await _asyncio.wait({_task}, timeout=120)
                    if pending:
                        _task.cancel()
                        try:
                            await _task
                        except BaseException:
                            pass
                        raise Exception(
                            "Image editing timed out (120s). "
                            "This may be due to Gemini server queueing. Please try again."
                        )
                    res = _task.result()
                else:
                    # Generate mode: no reference files
                    res = await adapter_router.generate_image(img_request, adapter=adapter)
                data = res.get("data", [])
                if not data:
                    raise ValueError("No images were generated by the model.")
                result = data[0].get("url", "")
            else:
                raise ValueError(f"Unknown task type: {task_type}")
            
            # Final validation: Ensure the result is a valid URL (absolute or root-relative)
            if not (str(result).startswith('http') or str(result).startswith('/')):
                raise ValueError(f"Generation failed to produce a valid URL. Internal Error: {result}")
                
            await JobManager.update_job(db, job_id, "completed", 1.0, result_url=result)
        except Exception as exc:
            await JobManager.update_job(db, job_id, "failed", 1.0, error=str(exc))


async def _create_task(task_type: str, request: TaskRequest, background_tasks: BackgroundTasks, db: AsyncSession):
    job = await JobManager.create_job(db, None, request.account_id, task_type)
    background_tasks.add_task(run_task_background, job.id, task_type, request.model_dump())
    return {"job_id": job.id, "status": "pending"}


@router.post("/image")
async def create_image_task(request: TaskRequest, background_tasks: BackgroundTasks, db: AsyncSession = Depends(get_db), user: User = Depends(get_user_by_key_or_jwt)):
    return await _create_task("image", request, background_tasks, db)


@router.post("/video")
async def create_video_task(request: TaskRequest, background_tasks: BackgroundTasks, db: AsyncSession = Depends(get_db), user: User = Depends(get_user_by_key_or_jwt)):
    return await _create_task("video", request, background_tasks, db)


@router.post("/music")
async def create_music_task(request: TaskRequest, background_tasks: BackgroundTasks, db: AsyncSession = Depends(get_db), user: User = Depends(get_user_by_key_or_jwt)):
    return await _create_task("music", request, background_tasks, db)


@router.post("/research")
async def create_research_task(request: TaskRequest, background_tasks: BackgroundTasks, db: AsyncSession = Depends(get_db), user: User = Depends(get_user_by_key_or_jwt)):
    return await _create_task("research", request, background_tasks, db)


@router.get("/{job_id}")
async def get_task_status(job_id: int, db: AsyncSession = Depends(get_db), user: User = Depends(get_user_by_key_or_jwt)):
    from backend.app.db.models import Account

    # Use select to join with account
    stmt = select(Job).where(Job.id == job_id)
    result = await db.execute(stmt)
    job = result.scalar_one_or_none()

    if not job:
        raise HTTPException(status_code=404, detail="Job not found")

    account_label = "unknown"
    if job.account_id:
        account = await db.get(Account, job.account_id)
        if account:
            account_label = account.label

    return {
        "job_id": job.id,
        "type": job.job_type,
        "status": job.status,
        "progress": job.progress_pct,
        "result_url": job.result_url,
        "error": job.error,
        "metadata": {
            "account": account_label,
            "created_at": job.created_at.isoformat() if job.created_at else None
        }
    }
