from pathlib import Path
from typing import Optional

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession

from backend.app.auth.api_key_auth import get_user_by_key_or_jwt
from backend.app.db.engine import AsyncSessionLocal, get_db
from backend.app.db.models import Job, User
from backend.app.jobs.manager import JobManager
from backend.app.schemas.native import ImageGenerationRequest
from pydantic import BaseModel

router = APIRouter(prefix="/native/tasks", tags=["native-tasks"])


class TaskRequest(BaseModel):
    prompt: str
    model: Optional[str] = None
    reference_file_ids: list[str] = []
    account_id: Optional[int] = None


async def run_task_background(job_id: int, task_type: str, request_data: dict):
    async with AsyncSessionLocal() as db:
        await JobManager.update_job(db, job_id, "processing", 0.1)
        prompt = request_data.get("prompt", "")
        model = request_data.get("model")
        reference_file_ids = request_data.get("reference_file_ids", [])
        account_id = request_data.get("account_id")
        try:
            if task_type == "video":
                from backend.app.adapters.mcpcli_adapter import McpCliAdapter
                adapter = McpCliAdapter()
                reference_files = [Path(ref) for ref in reference_file_ids]
                result_obj = await adapter.generate_video(prompt, model=model, account_id=account_id, reference_files=reference_files, options={})
                result = str(result_obj.video_paths[0]) if result_obj.video_paths else ""
            elif task_type == "music":
                from backend.app.adapters.mcpcli_adapter import McpCliAdapter
                result = await McpCliAdapter().generate_music(prompt)
            elif task_type == "research":
                from backend.app.adapters.mcpcli_adapter import McpCliAdapter
                result = await McpCliAdapter().deep_research(prompt)
            elif task_type == "image":
                from backend.app.api.openai.chat_completions import adapter_router
                res = await adapter_router.generate_image(ImageGenerationRequest(prompt=prompt, model=model, reference_file_ids=reference_file_ids, account_id=account_id))
                data = res.get("data", [])
                if not data:
                    raise ValueError("No images were generated by the model.")
                result = data[0].get("url", "")
            else:
                raise ValueError(f"Unknown task type: {task_type}")
            await JobManager.update_job(db, job_id, "completed", 1.0, result_url=result)
        except Exception as exc:
            await JobManager.update_job(db, job_id, "failed", 1.0, error=str(exc))


async def _create_task(task_type: str, request: TaskRequest, background_tasks: BackgroundTasks, db: AsyncSession):
    job = await JobManager.create_job(db, None, request.account_id, task_type)
    background_tasks.add_task(run_task_background, job.id, task_type, request.model_dump())
    return {"job_id": job.id, "status": "pending"}


@router.post("/image")
async def create_image_task(request: TaskRequest, background_tasks: BackgroundTasks, db: AsyncSession = Depends(get_db), user: User = Depends(get_user_by_key_or_jwt)):
    return await _create_task("image", request, background_tasks, db)


@router.post("/video")
async def create_video_task(request: TaskRequest, background_tasks: BackgroundTasks, db: AsyncSession = Depends(get_db), user: User = Depends(get_user_by_key_or_jwt)):
    return await _create_task("video", request, background_tasks, db)


@router.post("/music")
async def create_music_task(request: TaskRequest, background_tasks: BackgroundTasks, db: AsyncSession = Depends(get_db), user: User = Depends(get_user_by_key_or_jwt)):
    return await _create_task("music", request, background_tasks, db)


@router.post("/research")
async def create_research_task(request: TaskRequest, background_tasks: BackgroundTasks, db: AsyncSession = Depends(get_db), user: User = Depends(get_user_by_key_or_jwt)):
    return await _create_task("research", request, background_tasks, db)


@router.get("/{job_id}")
async def get_task_status(job_id: int, db: AsyncSession = Depends(get_db), user: User = Depends(get_user_by_key_or_jwt)):
    job = await db.get(Job, job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    return {"job_id": job.id, "type": job.job_type, "status": job.status, "progress": job.progress_pct, "result_url": job.result_url, "error": job.error}
